name: test

on:
  push:
    branches: [ 'master' ]
  pull_request:

permissions: read-all

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        timeout-minutes: 5
        with:
          version: latest
