name: test

on:
  push:
    branches: [ 'master' ]
  pull_request:

permissions: read-all

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'

      - name: Run Go tests
        run: go test ./...
